language: swift
osx_image: xcode10
script:
  - xcodebuild clean test -project cmark-gfm-swift.xcodeproj -scheme cmark-gfm-swift -destination "platform=iOS Simulator,name=iPhone X,OS=12.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet